# Generated by Django 3.2.25 on 2024-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fibonacci', models.FloatField()),
                ('Conruido', models.FloatField()),
                ('Error', models.FloatField()),
            ],
        ),
    ]
