# Generated by Django 3.2.25 on 2024-09-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_fibonacci_fibonacci_fibonaccic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonacci',
            old_name='Conruido',
            new_name='conruido',
        ),
        migrations.RenameField(
            model_name='fibonacci',
            old_name='Error',
            new_name='error',
        ),
        migrations.RenameField(
            model_name='fibonacci',
            old_name='Fibonaccic',
            new_name='fibonaccic',
        ),
    ]
