# Generated by Django 3.2.25 on 2024-10-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tienda', '0005_cosineaproximation_sineaproximation_tangentaproximation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTClient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
