# Generated by Django 3.2.25 on 2024-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_iotclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonacci',
            old_name='fibonaccic',
            new_name='fibonacci',
        ),
        migrations.RemoveField(
            model_name='fibonacci',
            name='conruido',
        ),
        migrations.AddField(
            model_name='fibonacci',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fibonacci',
            name='n',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
