# Generated by Django 3.2.25 on 2024-11-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20241104_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrumHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('value', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
