
services:
  app:                                  #Service name
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db && \
             python manage.py migrate && \
            python -m uvicorn app.asgi:application --host 0.0.0.0 --port 8080 --ws 'websockets' --ws-ping-interval=1000 --ws-ping-timeout=1000 --workers 1 --loop 'uvloop' --reload"
  #daphne -b 0.0.0.0 -p 8080 --websocket_timeout=-1  --ping-interval=0 --ping-timeout=1000 app.asgi:application"
  #           python manage.py runserver 0.0.0.0:8080"
  #  --certificate /etc/ssl/certs/cert.pem --key /etc/ssl/private/key.pem"
  
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb             #Local dev DataBase configuration for instalation
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data: #volume name, if left blank docker will assign it automatically
  dev-static-data: