# Generated by Django 3.2.25 on 2024-12-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airdrum', '0002_auto_20241208_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='duration',
        ),
    ]
