# Generated by Django 3.2.25 on 2024-12-09 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrum', '0003_remove_notes_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='time',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=1000, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
